### ISSUE TITLE
Getting error while recording audio. 

### ISSUE THREAD

**Issue by AnshulJain1985** [streamer45/mattermost-plugin-voice#4]
Hi

I am getting error while trying to record sound. tried on mobile and chrome and safari.
Also gave permission to record audio.
Can you please check.
com.mattermost.voice_5e23551578f984bc_bundle.js:1 Uncaught (in promise) Error: unsupported
    at n._startCapture (com.mattermost.voice_5e23551578f984bc_bundle.js:1)
    at n.start (com.mattermost.voice_5e23551578f984bc_bundle.js:1)
    at Object.startRecording (com.mattermost.voice_5e23551578f984bc_bundle.js:9)
    at com.mattermost.voice_5e23551578f984bc_bundle.js:9
    at Object.e.registerFileUploadMethod.M.id [as action] (com.mattermost.voice_5e23551578f984bc_bundle.js:9)
    at onClick (file_upload.jsx:633)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at M (react-dom.production.min.js:15)
    at react-dom.production.min.js:15
    at y (react-dom.production.min.js:17)

**Comment by cazeredodev** [comment]
Hi, same problem. Any solution?

**Comment by domcars0** [comment]
Same here, while trying  with Firefox 74 for Ubuntu :-(

**Comment by streamer45** [comment]
@AnshulJain1985 

Thank you for your report. I apologize for the very late reply.  I'll look into this and let you know.

**Comment by streamer45** [comment]
From the error it looks like the browser is either very outdated or you are running on an insecure website.
For the capture to be possible the connection to the server needs to be secured (use HTTPs).
This is a browser limitation/security feature so nothing we can fix. More info [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 8.6. bis zum 12.6. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
Closed #4.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/streamer45/mattermost-plugin-voice/issues/4#event-3421297316
